In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import time
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

X = list()
Y = list()
X = [x+1 for x in range(50)]
Y = [y * 5 for y in X]

print(X)
print(Y)




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250]


In [ ]:
X=array(X).reshape(50, 1, 1)
X=np.array(X)
Y=np.array(Y)
model = Sequential()
model.add(LSTM(2,activation='relu', input_shape=(1, 1))) 
model.add(Dense(1,activation='linear')) 
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, Y, epochs=50000, verbose=0) 
yhat = model.predict(X, verbose=0) 
print(yhat)

[[  5.002679]
 [  9.997906]
 [ 14.998606]
 [ 20.00021 ]
 [ 25.001328]
 [ 30.001753]
 [ 35.001644]
 [ 40.001232]
 [ 45.000694]
 [ 50.000137]
 [ 54.999653]
 [ 59.999252]
 [ 64.998955]
 [ 69.99877 ]
 [ 74.99868 ]
 [ 79.998665]
 [ 84.99871 ]
 [ 89.99885 ]
 [ 94.99899 ]
 [ 99.999176]
 [104.9994  ]
 [109.99962 ]
 [114.99983 ]
 [120.00005 ]
 [125.00027 ]
 [130.00047 ]
 [135.00066 ]
 [140.00084 ]
 [145.00099 ]
 [150.00111 ]
 [155.0012  ]
 [160.00128 ]
 [165.00134 ]
 [170.00136 ]
 [175.00136 ]
 [180.00131 ]
 [185.00127 ]
 [190.0012  ]
 [195.00107 ]
 [200.00095 ]
 [205.0008  ]
 [210.00063 ]
 [215.00043 ]
 [220.00021 ]
 [224.99995 ]
 [229.99968 ]
 [234.9994  ]
 [239.99915 ]
 [244.9988  ]
 [249.99847 ]]


In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 2)                 32        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [ ]:
test_input = array([153])
test_input = test_input.reshape((1, 1, 1)) 
test_output = model.predict(test_input, verbose=0) 
print(test_output)


[[764.9406]]


In [ ]:
for layer in model.layers: 
    if "LSTM" in str(layer):
        weightLSTM = layer.get_weights() 
    else:
        weightLSTM_dense=layer.get_weights()

from numpy import exp 
test_input = array([153])
test_input = test_input.reshape((1, 1, 1))
 

test_output = model.predict(test_input, verbose=0)
print("Shapeof the model: W ",model.get_weights()[0].shape,'\n',model.get_weights() [0])

print("model.layers[0].trainable_weights:\n")
print(model.layers[0].trainable_weights) 
print("model.layers[1].trainable_weights:\n")
print(model.layers[1].trainable_weights) 
def sigmoid(x):
    return(1.0/(1.0+np.exp(-x))) 
def softmax(x):
    e = exp(x)
    return e / e.sum() 
def relu(input):
    print(input) 
    if input > 0:
        return input 
    else:
        return 0
    
units=2 
x_t=test_input
print("x_t :",x_t)
h_tm1 = np.array([0]*units).reshape(1,units) 
print("h_tm1 :",h_tm1)
c_tm1 = np.array([0]*units).reshape(1,units)
print("c_tm1 :",c_tm1) 
W = model.layers[0].get_weights()[0]
print("W :",W)
U = model.layers[0].get_weights()[1]
print("U :",U) 
b = model.layers[0].get_weights()[2]
print("b :",b)

W_i = W[:, :units]
W_f = W[:, units: units * 2]
W_c = W[:, units * 2: units * 3] 
W_o = W[:, units * 3:]

U_i = U[:, :units]
U_f = U[:, units: units * 2]
U_c = U[:, units * 2: units * 3] 
U_o = U[:, units * 3:]

b_i = b[:units]
b_f = b[units: units * 2]
b_c = b[units * 2: units * 3] 
b_o = b[units * 3:]

print("w_i",W_i,"\n w_f:",W_f,"\nw_c:",W_c,"\n w_o:",W_o)
print("U_i",U_i,"\n U_f:",U_f,"\nU_c:",U_c,"\n U_o:",U_o)
print("b_i",b_i,"\n b_f:",b_f,"\nb_c:",b_c,"\n b_o:",b_o) 
print("\n")
print("x_t.dot(W_i) :",x_t.dot(W_i))
print("h_tm1.dot(U_i) :",h_tm1.dot(U_i))
i1 = (x_t.dot(W_i) + h_tm1.dot(U_i) + b_i) 
print("i1 :",i1)
i_t=sigmoid(i1)
print("Input Gate i_t",np.round(i_t,7)) 
print("\n")
print("x_t.dot(W_f) :",x_t.dot(W_f))
print("h_tm1.dot(U_f) :",h_tm1.dot(U_f))
f1=(x_t.dot(W_f) + h_tm1.dot(U_f) + b_f) 
print("f1 :",f1)
f_t=sigmoid(f1)
print("Forget gate f_t",np.round(f_t,7)) 

print("\n")
print("x_t.dot(W_c)",x_t.dot(W_c)) 
print("h_tm1.dot(U_c)",h_tm1.dot(U_c)) 
c_tcomplement=(x_t.dot(W_c) + h_tm1.dot(U_c) + b_c)

print("c1",c_tcomplement)
for i in (0,c_tcomplement.size-1): 
    c_tcomplement[0][0][i]=relu(c_tcomplement[0][0][i])
 
print("Cell gate (Part 1)c_tcomplement",c_tcomplement) 
print("\n")
print("x_t.dot(W_o)",x_t.dot(W_o))
print("h_tm1.dot(U_o)",h_tm1.dot(U_o))
o1=(x_t.dot(W_o) + h_tm1.dot(U_o) + b_o)
print("o1 :",o1) 
o_t=sigmoid(o1)
print("Output gate o_t",np.round(o_t,7)) 
print("\n")
print("i_t*(c_tcomplement) :",i_t*(c_tcomplement))
print("f_t*(c_tm1) :",f_t*(c_tm1))
c_t=(i_t*(c_tcomplement)+ f_t*(c_tm1)) 
print("c_t :",c_t) 
print("Cell gate (Part2) c_t",c_t)
for i in (0,c_t.size-1): 
    c_t[0][0][i]=relu(c_t[0][0][i])
print("\n")
h_t = o_t*((c_t)) 
print("Hidden State h_t",h_t)

print("\nWeights of dense Layer W_v",weightLSTM_dense[0],"\nDense Layer bias b_v",weightLSTM_dense[1])
W_v=weightLSTM_dense[0] 
b_v=weightLSTM_dense[1] 
print("h_t.dot(W_v)",h_t.dot(W_v))
v_t=h_t.dot(W_v)+b_v 
print("Calculated Output v_t",v_t)


print("\nInput",test_input)
print("Predicted output",model.predict([[[153]]], verbose=0))

Shapeof the model: W  (1, 8) 
 [[ 0.06774777  0.08743153 -0.5398437   0.44428802 -0.2352066   2.4221814
  -0.7542955   0.63557214]]
model.layers[0].trainable_weights:

[<tf.Variable 'lstm_3/lstm_cell_3/kernel:0' shape=(1, 8) dtype=float32, numpy=
array([[ 0.06774777,  0.08743153, -0.5398437 ,  0.44428802, -0.2352066 ,
         2.4221814 , -0.7542955 ,  0.63557214]], dtype=float32)>, <tf.Variable 'lstm_3/lstm_cell_3/recurrent_kernel:0' shape=(2, 8) dtype=float32, numpy=
array([[ 0.3372755 ,  0.73035806,  0.22406198,  0.01914683, -0.03432008,
         0.30748627,  0.21941452,  0.39797446],
       [-0.65534425,  0.06862415, -0.34464717, -0.2082873 , -0.34570518,
         0.21056055, -0.07719273,  0.483573  ]], dtype=float32)>, <tf.Variable 'lstm_3/lstm_cell_3/bias:0' shape=(8,) dtype=float32, numpy=
array([0.       , 6.72526  , 1.       , 1.       , 0.       , 0.4026067,
       0.       , 4.9155555], dtype=float32)>]
model.layers[1].trainable_weights:

[<tf.Variable 'dense_3/kernel:0' sha